### ISSUE TITLE
is it possible to use with babel/preset-typescript ?

### ISSUE THREAD

**Issue by vladmelnikov** [wessberg/DI-compiler#9]
is it possible to use with babel/preset-typescript ?

**Comment by wessberg** [comment]
No, because `babel/preset-typescript` is strictly performing syntax transformations and has no type awareness or knowledge of the internal structure of your program. That is also the primary reason why it is fast. `DI-Compiler` requires a type checker such that it can trace symbols back to a `DIContainer`, and for that a proper TypeScript program is needed.
